// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUs20gXMQJ0XSVEzsHaWTwwW_sroXV-Ms',
    appId: '1:364705335202:web:e7a838180cfe8735a614fb',
    messagingSenderId: '364705335202',
    projectId: 'academitrack-b195c',
    authDomain: 'academitrack-b195c.firebaseapp.com',
    storageBucket: 'academitrack-b195c.firebasestorage.app',
    measurementId: 'G-F613WEDWH8',
    databaseURL:
        'https://academitrack-b195c-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkU35Lghs48wsECUTwtxmNRTYgKLmKS08',
    appId: '1:364705335202:android:0f4dac8407de6abca614fb',
    messagingSenderId: '364705335202',
    projectId: 'academitrack-b195c',
    storageBucket: 'academitrack-b195c.firebasestorage.app',
    databaseURL:
        'https://academitrack-b195c-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBawfZwd03sd4iVMmkAuIqIaJrpzA0SAs8',
    appId: '1:364705335202:ios:d22f79aad10ec62da614fb',
    messagingSenderId: '364705335202',
    projectId: 'academitrack-b195c',
    storageBucket: 'academitrack-b195c.firebasestorage.app',
    iosBundleId: 'com.example.academitrack',
    databaseURL:
        'https://academitrack-b195c-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBawfZwd03sd4iVMmkAuIqIaJrpzA0SAs8',
    appId: '1:364705335202:ios:d22f79aad10ec62da614fb',
    messagingSenderId: '364705335202',
    projectId: 'academitrack-b195c',
    storageBucket: 'academitrack-b195c.firebasestorage.app',
    iosBundleId: 'com.example.academitrack',
    databaseURL:
        'https://academitrack-b195c-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUs20gXMQJ0XSVEzsHaWTwwW_sroXV-Ms',
    appId: '1:364705335202:web:941a47433bb45a31a614fb',
    messagingSenderId: '364705335202',
    projectId: 'academitrack-b195c',
    authDomain: 'academitrack-b195c.firebaseapp.com',
    storageBucket: 'academitrack-b195c.firebasestorage.app',
    measurementId: 'G-GCY4H0LL8N',
    databaseURL:
        'https://academitrack-b195c-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
